[platformio]
default_envs = esp32s, esp32s_ota_1, esp32s_ota_2

[env:esp32s]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_protocol = esptool
upload_port = COM6
monitor_port = COM6
lib_deps = 
	milesburton/DallasTemperature
	paulstoffregen/OneWire
	LiquidCrystal_I2C
	mikalhart/TinyGPSPlus@^1.1.0

[env:esp32s_ota_1]
extends = env:esp32s
upload_protocol = espota
upload_port = 192.168.100.168
upload_flags =
	--timeout=30
	--host_ip=192.168.100.60
	--host_port=3233

[env:esp32s_ota_2]
extends = env:esp32s
upload_protocol = espota
upload_port = 172.31.58.164
upload_flags =
	--timeout=30
	--host_ip=192.168.100.60
	--host_port=3233