[env:esp32s]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_protocol = esptool
upload_port = COM5
monitor_port = COM5
lib_deps = 
	milesburton/DallasTemperature
	paulstoffregen/OneWire
	LiquidCrystal_I2C
	mikalhart/TinyGPSPlus@^1.1.0

[env:esp32s_ota]
extends = env:esp32s
upload_protocol = espota
upload_port = 192.168.100.168
upload_flags =
	--timeout=30
	--host_ip=192.168.100.122
	--host_port=3233