[env:esp32s]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_protocol = esptools
upload_port = COM4
monitor_port = COM4
lib_deps = 
	milesburton/DallasTemperature
	paulstoffregen/OneWire
	LiquidCrystal_I2C
	mikalhart/TinyGPSPlus@^1.1.0